[package]
org = "user"
name = "BinBuddy"
version = "0.1.0"
distribution = "2201.12.9"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.11.0"

[[dependency]]
org = "ballerinax"
name = "mysql.driver"
version = "1.6.0"

[[dependency]]
org = "ballerinax"
name = "mssql"
version = "1.7.0"

[[dependency]]
org = "ballerinax"
name = "mssql.driver"
version = "1.6.0"
